using Pkg
Pkg.add("Downloads")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("CodecBzip2")
Pkg.add("Tar")
Pkg.add("Graphs")
Pkg.add("Printf")
Pkg.add("LinearAlgebra")
Pkg.add("StatsBase")
Pkg.add("SortingAlgorithms")
Pkg.add("Plots")