const DATASET_NAME = "wordnet-words"
const DATASET_URL = "http://konect.cc/files/download.tsv.wordnet-words.tar.bz2"
const DOWNLOADS_FOLDER = joinpath(pwd(), "downloads")
const DATASETS_FOLDER = joinpath(pwd(), "$DATASET_NAME")
const GRAPHS_FOLDER = joinpath(pwd(), "graphs")
const DATASET_FILENAME_BZ2 = "$DATASET_NAME.tar.bz2"
const GRAPH_PATH = joinpath(DATASETS_FOLDER, DATASET_NAME)
const GRAPH_FILENAME_TSV = "out.wordnet-words"
const GRAPH_FILENAME_LG = "$DATASET_NAME.lg"
const GRAPH_FILENAME_MAXCC_LG = "$DATASET_NAME.maxcc.lg"